### ISSUE TITLE
Create save a url shortner feature

### ISSUE THREAD

**Issue by gabrielcancio** [gabrielcancio/nodejs-url-shortner-api#1]
**📍Goal:**  The regular should be able to create a shortned url from a original link, and the genereated url should have a default 30 days time to expires.

**✅Tasks:**
- [x] Raise requirements
- [x] Implement domain business rules
- [x] Implement application issues
- [ ] Implement infra issues

**Comment by gabrielcancio** [comment]
The first is raise requisites to make the feature.

### Raised requistes:

* Should be able to create a shortned
* Should not able to create a shortned url of a nonexistent url(empty url)
* Should the created shortned url have a expiration time of 30 days.
* Should be able to set the shortned url as a alias given by user
* Should not be able save a shortened url with blank spaces chars in alias given by user, replace the blank spaces in the middle of alias by hyphen instead, and blank spaces on start or end should be trimed.
* Should not be able save a shortned url by user alias that exists
* Should not be able to save a random generated url(generated by hashing) that already exists, regenerated until the generated url is unique
* Should not be able to save an shortned url with an alias bigger than 20 characters

**Comment by gabrielcancio** [comment]
### ⚒Worked today:
- Add the requirement to length of alias.
- Refacted the domain to distributing the responsabilities between the ShortnedUrl, UrlHash and Alias classes.
- Refacted the use case to use the domain classes

**Comment by gabrielcancio** [comment]
### 🔧Implementing infra issues:
**📋Requirements**
* Should be able to make a POST request to ending point /shortned-url to create a shortned url
    - Payload should be original url.
    - Response should be generated url and expiration time(30 days)
    - HTTP Code returned should be 201 with generated shortned url and expiration date
* Should not able to create a shortned url of a nonexistent url(empty url)
    - Payload should be empty
    - Responses shoud have a message with the error message
    - HTTP status code should be 400
* Should be able to set the shortned url as a alias given by user
    - Payload should be original url and alias
    - Response should be generatedUrl(It contains alias) and expiration time
    - HTTP status code should be 201
* Should not be able save a shortned url by user alias that exists
    - Payload should be original url and alias
    - Responses shoud have a message with the error message
    - HTTP status code should be 400
* Should not be able save a shortened url with blank spaces chars in alias given by user
    - Payload should be original url and alias
    - Response should be generatedUrl(It contains alias, sanitized) and expiration time
    - HTTP status code should be 201
* Should not be able to save an shortned url with an alias bigger than 20 characters
    - Payload should be original url and alias (With more than 20 chars)
    - Responses shoud have a message with the error message
    - HTTP status code should be 400

**🧪Environment requirements**
- Implement the http layer to run the tests
- Implement the database layear and prepare it for tests
- Possible libs to use:
-  Supertest for http requests
